# Generated by Django 5.2.11 on 2026-03-30 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(help_text='MovieLens movieId', primary_key=True, serialize=False)),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('genres', models.CharField(default='', max_length=500)),
                ('overview', models.TextField(default='')),
                ('original_language', models.CharField(default='en', max_length=10)),
                ('popularity', models.FloatField(default=0)),
                ('vote_average', models.FloatField(default=0)),
                ('poster_path', models.CharField(default='', max_length=300)),
                ('backdrop_path', models.CharField(default='', max_length=300)),
                ('keywords', models.TextField(default='')),
                ('release_date', models.CharField(default='', max_length=20)),
                ('tagline', models.CharField(default='', max_length=500)),
            ],
            options={
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('preferred_languages', models.CharField(default='en', max_length=200)),
                ('favorite_genres', models.CharField(default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('rating', models.FloatField()),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recommender.movie')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'rating'], name='recommender_user_id_a710b8_idx')],
                'unique_together': {('user_id', 'movie')},
            },
        ),
    ]
