# Generated by Django 6.0.3 on 2026-03-30 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_alter_rating_rating_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('review_text', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='recommender.movie')),
            ],
            options={
                'indexes': [models.Index(fields=['movie', 'created_at'], name='recommender_movie_i_3425f5_idx'), models.Index(fields=['user_id', 'updated_at'], name='recommender_user_id_b2f895_idx')],
                'unique_together': {('user_id', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='WatchedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='recommender.movie')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'watched_at'], name='recommender_user_id_31305a_idx')],
                'unique_together': {('user_id', 'movie')},
            },
        ),
    ]
