# Generated by Django 5.2.11 on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0004_rating_scale_to_ten_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="movie",
            name="original_language",
            field=models.CharField(db_index=True, default="en", max_length=10),
        ),
        migrations.AlterField(
            model_name="movie",
            name="popularity",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="movie",
            name="vote_average",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["original_language", "popularity"],
                name="rec_movie_lang_pop_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["vote_average", "popularity"],
                name="rec_movie_vote_pop_idx",
            ),
        ),
    ]
