# Generated by Django 5.2.11 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0005_movie_indexes_optimization"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rating",
            index=models.Index(
                fields=["user_id", "timestamp"],
                name="rec_rating_user_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["movie", "updated_at", "created_at"],
                name="rec_review_movie_recent_idx",
            ),
        ),
    ]
